# Try Pulling the image from 'ghcr.io/hallboard-team/'
#   Builds the image if NOT exists.
# Create a container off the image and run it. 

version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        DOTNET_VERSION: ${DOTNET_VERSION:-9.0}

    image: ghcr.io/hallboard-team/dotnet-v${DOTNET_VERSION}:latest
    container_name: ${CONTAINER_NAME}

    user: "1000:1000"

    volumes:
      - ./:/workspaces/app:Z
      - ~/.cache/vscode-server-shared:/home/vscode/.vscode-server-shared:Z

    environment:
      - REMOTE_USER=vscode
      - VSCODE_SERVER_DIR=/home/vscode/.vscode-server-shared

    ports:
      - "${PORT:-5000}:5000"

    command: >
      bash -c "
        dotnet --info &&
        sleep infinity
      "
